# Generated by Django 3.2.7 on 2024-01-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=100)),
                ('uphone', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=100)),
            ],
        ),
    ]
