# Generated by Django 3.2.7 on 2024-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('pdescription', models.CharField(max_length=100)),
                ('pqty', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=100)),
                ('pfile', models.FileField(upload_to='')),
            ],
        ),
    ]
