# Generated by Django 3.2.7 on 2024-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urid', models.CharField(max_length=100)),
                ('prcode', models.CharField(max_length=100)),
                ('prname', models.CharField(max_length=100)),
                ('prprice', models.CharField(max_length=100)),
                ('prqty', models.CharField(max_length=100)),
                ('prfile', models.FileField(upload_to='')),
            ],
        ),
    ]
