# Generated by Django 3.2.7 on 2024-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pdescription',
            field=models.CharField(max_length=3000),
        ),
    ]
